### ISSUE TITLE
Usage with Sapper

### ISSUE THREAD

**Issue by ditorahard** [nathancahill/sveltik#133]
When I go to develop this using sapper I got this error :

`Sveltik is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

Is there currently any fix or workaround with this? Many thanks

**Comment by stregouet** [comment]
you should but it in `devDependencies` see https://github.com/sveltejs/sapper-template#using-external-components

**Comment by nathancahill** [comment]
This is correct.
