### ISSUE TITLE
Pass class names as props to HTML tags

### ISSUE THREAD

**Issue by websocket98765** [nathancahill/sveltik#210]
Idea. From a cursory look at [Field.svelte](https://github.com/nathancahill/sveltik/blob/master/src/Field.svelte), it doesn't appear possible to pass class names as properties to the final HTML tags (form, input, etc).

The ability to pass class names would allow styling these with TailwindCSS.

**Comment by nathancahill** [comment]
All extra properties are passed to the final HTML elements, including `class`. I've actually been using Tailwind with the library as it has developed.

**Comment by juzzin** [comment]
How do you handle adding classes when the Field has an error?
