### ISSUE TITLE
REPL has an error:

### ISSUE THREAD

**Issue by blazzjosh** [nathancahill/sveltik#99]
The REPL has an error:

Error: `$$restProps is an illegal variable name (Field.svelte:53:16)`
https://svelte.dev/repl/5ba56f98dc7f4911818ec5617c6b3024?version=3.19.0

**Comment by nathancahill** [comment]
Try with the latest version of Svelte: https://svelte.dev/repl/5ba56f98dc7f4911818ec5617c6b3024?version=3.23.0

**Comment by nathancahill** [comment]
`$$restProps` is a Svelte feature added in [3.20.0](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3200)
